/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bea51be8-5fbd-4055-b22c-ccb3b84ac343",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_X9pIz7JDc",
    "aws_user_pools_web_client_id": "bpdvso2o3seo491pho63olv73",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://sv7krnitu5cwjp7csuq7giszi4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
